version: "3.8"

services:
  app:
    build: .
    container_name: django_app
    ports:
      - "8000:8000"
    volumes:
      - media:/app/media
      - static:/app/static
    env_file:
      - .env.prod
    networks:
      - app_network

  nginx:
    image: nginx:latest
    ports:
      - "8001:80"
    #   - "443:443"
    depends_on:
      - app
    networks:
      - app_network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static:/app/static
      - media:/app/media

volumes:
  media:
  static:

networks:
  app_network:
