version: "3.8"

services:
  app:
    build: .
    container_name: django_app
    ports:
      - "8000:8000"
    volumes:
      - media:/app/media
      - static:/app/static
    env_file:
      - .env.prod
    environment:
      REDIS_URL: redis://mq:6379/0
    networks:
      - app_network
    depends_on:
      - mq

  nginx:
    image: nginx:latest
    ports:
      - "8001:80"
    #   - "443:443"
    networks:
      - app_network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static:/app/static
      - media:/app/media
    depends_on:
      - app

  mq:
    container_name: mq
    image: redis:8.0.3-alpine3.21
    ports:
      - "6379:6379"
    networks:
      - app_network
    volumes:
      - redis_data:/data

  worker:
    build: .
    volumes:
      - media:/app/media
      - static:/app/static
    command: celery -A ink_sphere worker --loglevel=info --pool=solo
    env_file:
      - .env.prod
    environment:
      REDIS_URL: redis://mq:6379/0
    networks:
      - app_network
    depends_on:
      - mq
      - app

volumes:
  media:
  static:
  redis_data:

networks:
  app_network:
