name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: 3.13

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: run code review
      run: bash fix_code.sh
        
    - name: Run flake8
      run: flake8 .
      
    # - name: Run Tests
    #   run: |
    #     python manage.py test

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: mouada/blog-app:1.0

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Execute remote SSH commands using SSH key
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            whoami
            docker stop blog-app-container || true
            docker rm blog-app-container || true
            docker pull mouada/blog-app:1.0
            docker run -d --name blog-app-container -p 8001:8001 mouada/blog-app:1.0