name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: 3.13

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run black
      uses: psf/black@stable
        
    - name: Check for unused imports with autoflake
      uses: creyD/autoflake_action@v1.1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          options: --in-place --remove-all-unused-imports -r
        
    - name: Run flake8
      run: flake8 .
      
    # - name: Run Tests
    #   run: |
    #     python manage.py test
